### ISSUE TITLE
Only 'tests' extra is required in setup.py

### ISSUE THREAD

**Issue by elioschmutz** [4teamwork/ftw.bob.module#3]
The `extras_require`-Dict contains `tests` and `test` but only `tests` is required. `test` will never be used.

https://github.com/4teamwork/ftw.bob.module/blob/master/ftw/bob/module/template/%2Bpackage.fullname%2B/setup.py.bob#L17

**Comment by raphael-s** [comment]
Done: https://github.com/4teamwork/ftw.bob.module/commit/550c60194512c7073b19943ef89f954893feff2f
